# Generated by Django 6.0 on 2025-12-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='emotion',
            field=models.CharField(choices=[('NEUTRAL', 'Neutral'), ('CONFIDENT', 'Confident'), ('ANXIOUS', 'Anxious'), ('GREEDY', 'Greedy'), ('FEARFUL', 'Fearful'), ('FOMO', 'FOMO')], default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_backtest',
            field=models.BooleanField(default=False, help_text='Check if this is a backtest/paper trade'),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='journal.strategy'),
        ),
    ]
