# Generated by Django 6.0 on 2025-12-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text/Markdown'), ('VIDEO', 'YouTube Video'), ('LINK', 'External Link')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_link',
            field=models.URLField(blank=True, help_text='External Resource Link', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube Video URL', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown text, YouTube URL, or External Link URL'),
        ),
    ]
